### PR TITLE
[WIP] Breadcrumb

### PR DESCRIPTION
**Pull request by jeremiehelme**
Adapting breadcrumb to the mockup :

Capture d’écran 2020-02-25 à 14 21 08

Capture d’écran 2020-02-25 à 14 22 16

### CODE REVIEW

**Comment by SamMousa** [comment]
Shouldn't there be a separator between the breadcrumbs?

**Comment by jeremiehelme** [comment]
Yes, sorry, I took the screenshot back when the icons weren't working on my local

**Comment by SamuelPetragallo** [comment]
Not sure if anything else than the look needs to be validated here  - ?

**Comment by SamMousa** [comment]
That's correct, the label `approve design` is about approving the design.

**Comment by jeremiehelme** [comment]
@SamuelPetragallo  It's not a big change, but it seems that you have to review and approve it so that we can merge it, when you have a minute :)

**Pull request closed without merging**
